import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
// import { ChatProvider } from "@/context/chat";
import "./globals.css";
import Providers from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SessionProvider session={null}>
            {children}
            <Toaster />
          </SessionProvider>
        </Providers>
        {/* <SessionProvider>{children}</SessionProvider> */}
      </body>
    </html>
  );
}
